name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build Linux binary
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0
        run: |
          go build -v -a -ldflags '-extldflags "-static"' -o freebsd-archive-combiner-linux-amd64 ./cmd/main.go

      - name: Build FreeBSD binary
        env:
          GOOS: freebsd
          GOARCH: amd64
          CGO_ENABLED: 0
        run: |
          go build -v -a -ldflags '-extldflags "-static"' -o freebsd-archive-combiner-freebsd-amd64 ./cmd/main.go

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            freebsd-archive-combiner-linux-amd64
            freebsd-archive-combiner-freebsd-amd64
          generate_release_notes: true
